name: app_analytics
description: "Reusable analytics package with multi-SDK support and extensibility"
version: 0.0.1
homepage: https://github.com/mixin27/app_analytics
issue_tracker: https://github.com/mixin27/app_analytics/issues

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # FP Dart
  fpdart: ^1.2.0

  # Data Models and JSON Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0

  # Async Utilities
  async: ^2.13.0

  # Platform
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0

  # Analytics
  firebase_analytics: ^12.1.2
  mixpanel_flutter: ^2.5.0
  amplitude_flutter: ^4.3.10

  # HTTP
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  commitlint_cli: ^0.8.1
  husky: ^0.1.7
  build_runner: ^2.11.0
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  mockito: ^5.6.3
